module.exports = {
  sidebar: [
    {
			type: 'category',
			label: 'General',
			items: ['general/welcome'],
			collapsed: false
		},
    {
			type: 'category',
			label: 'Documentation',
			collapsed: true,
			items: [
				{
					type: 'autogenerated',
					dirName: 'documentation'
				}
			]
		}
  ]
}
